# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/literatura_db
spring.datasource.username=seu usuario
spring.datasource.password=sua senha
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate 
# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
