# Configura��o do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/literatura_db
spring.datasource.username=postgres
spring.datasource.password=290619Ba.
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��es do JPA/Hibernate - ESTA LINHA � CRUCIAL!
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true